name: tourney
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.4.5
  supabase_flutter: ^2.8.2
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_dotenv: ^5.0.2


flutter:
  uses-material-design: true
